/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useCallback } from "react";
import { Header } from "./components/Header";
import { ThunderClient } from "./components/ThunderClient";
import { DatabaseExplorer } from "./components/DatabaseExplorer";
import { ServerConsole } from "./components/ServerConsole";
import { ApiDocs } from "./components/ApiDocs";
import { BlogPost, RequestLog } from "./types";

export default function App() {
  const [activeTab, setActiveTab] = useState<'thunder' | 'database' | 'console' | 'docs'>('thunder');
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [logs, setLogs] = useState<RequestLog[]>([]);
  const [serverOnline, setServerOnline] = useState<boolean>(true);
  const [isLoadingPosts, setIsLoadingPosts] = useState<boolean>(false);
  const [isLoadingLogs, setIsLoadingLogs] = useState<boolean>(false);
  const [isSeeding, setIsSeeding] = useState<boolean>(false);

  // Fetch all posts from in-memory database (GET /posts)
  const fetchPosts = useCallback(async () => {
    setIsLoadingPosts(true);
    try {
      const res = await fetch("/posts");
      if (res.ok) {
        const data = await res.json();
        setPosts(Array.isArray(data) ? data : []);
        setServerOnline(true);
      }
    } catch (e) {
      setServerOnline(false);
    } finally {
      setIsLoadingPosts(false);
    }
  }, []);

  // Fetch server console logs generated by custom middleware
  const fetchLogs = useCallback(async () => {
    setIsLoadingLogs(true);
    try {
      const res = await fetch("/api/logs");
      if (res.ok) {
        const data = await res.json();
        setLogs(Array.isArray(data) ? data : []);
      }
    } catch (e) {
      // Ignore background log fetch error
    } finally {
      setIsLoadingLogs(false);
    }
  }, []);

  // Check initial server health and fetch initial state
  useEffect(() => {
    fetchPosts();
    fetchLogs();

    // Periodic polling to keep server logs and posts synchronized
    const interval = setInterval(() => {
      fetchLogs();
    }, 2500);

    return () => clearInterval(interval);
  }, [fetchPosts, fetchLogs]);

  // Seed standard posts helper
  const handleSeed = async () => {
    setIsSeeding(true);
    try {
      const res = await fetch("/api/seed", { method: "POST" });
      if (res.ok) {
        await fetchPosts();
        await fetchLogs();
      }
    } catch (e) {
      alert("Failed to seed database.");
    } finally {
      setIsSeeding(false);
    }
  };

  // Reset in-memory database to empty array (let blogPosts = [])
  const handleReset = async () => {
    if (!confirm("Reset in-memory database to empty array (let blogPosts = [])?")) return;
    try {
      const res = await fetch("/api/reset", { method: "POST" });
      if (res.ok) {
        await fetchPosts();
        await fetchLogs();
      }
    } catch (e) {
      alert("Failed to reset database.");
    }
  };

  // Clear server console logs
  const handleClearLogs = async () => {
    try {
      await fetch("/api/logs", { method: "DELETE" });
      setLogs([]);
    } catch (e) {
      alert("Failed to clear server logs.");
    }
  };

  // Switch to Thunder Client with specific post and method
  const handleSelectPostForThunderClient = (id: string, method: 'GET' | 'PUT' | 'DELETE') => {
    setActiveTab('thunder');
  };

  return (
    <div className="min-h-screen bg-neutral-100 text-neutral-900 flex flex-col font-sans antialiased">
      {/* Top Application Navigation & Server Status Bar */}
      <Header
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        postCount={posts.length}
        serverOnline={serverOnline}
        onSeed={handleSeed}
        onReset={handleReset}
        isSeeding={isSeeding}
      />

      {/* Main Content Workspace */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6">
        {activeTab === 'thunder' && (
          <ThunderClient
            onRefreshDatabase={fetchPosts}
            onPostCreated={() => {
              fetchPosts();
              fetchLogs();
            }}
          />
        )}

        {activeTab === 'database' && (
          <DatabaseExplorer
            posts={posts}
            isLoading={isLoadingPosts}
            onRefresh={fetchPosts}
            onSeed={handleSeed}
            onReset={handleReset}
            onSelectPostForThunderClient={handleSelectPostForThunderClient}
          />
        )}

        {activeTab === 'console' && (
          <ServerConsole
            logs={logs}
            isLoading={isLoadingLogs}
            onRefresh={fetchLogs}
            onClearLogs={handleClearLogs}
          />
        )}

        {activeTab === 'docs' && <ApiDocs />}
      </main>

      {/* Engineering Footer */}
      <footer className="border-t border-neutral-200 bg-white py-4 text-xs text-neutral-500">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-2">
          <div className="flex items-center space-x-2">
            <span className="font-semibold text-neutral-700">The Data Hub</span>
            <span>•</span>
            <span>RESTful API Server Architecture Sprint</span>
          </div>
          <div className="flex items-center space-x-1.5 text-neutral-700 font-medium">
            <span>Built with</span>
            <span className="text-rose-500 inline-block animate-pulse" aria-label="love">❤️</span>
            <span>by <strong className="text-neutral-900 font-semibold">Alok Kumar Mishra</strong></span>
          </div>
          <div className="flex items-center space-x-3 font-mono text-[11px] text-neutral-400">
            <span>[Phase 1] Scaffolding</span>
            <span>•</span>
            <span>[Phase 2] CRUD</span>
            <span>•</span>
            <span>[Phase 3] Logs & Auth</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
